name: Pylint

on:
  push:
    branches:
      - main  # À ajuster en fonction de votre branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

      # Ajout d'une vérification conditionnelle pour empêcher le push en cas d'erreurs
      - name: Check Pylint result
        run: |
          pylint_exit_code=$?
          if [ $pylint_exit_code -ne 0 ] && [ $pylint_exit_code -ne 30 ]; then
            echo "Pylint found errors. Exiting..."
            exit 1
          fi
