name: Pylint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint_exit_code=0
          pylint --disable=C0305,C0114,E0401,R0903 $(git ls-files '*.py') || pylint_exit_code=$?
          if [ $pylint_exit_code -ne 0 ] && [ $pylint_exit_code -ne 30 ]; then
            echo "Pylint found errors. Exiting..."
            exit 1
          fi
          pylint_score=$(pylint --score=n $(git ls-files '*.py') | awk '{print $2}')
          if (( $(echo "$pylint_score < 9" | bc -l) )); then
            echo "Pylint score is below 9. Exiting..."
            exit 1
          fi
